apiVersion: v1
kind: Namespace
metadata:
  name: test-cronjob
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cronjob
  namespace: test-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-cronjob
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure