apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server
        image: nginx
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
          - name: nginx
            mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx
        persistentVolumeClaim:
          claimName: longhorn-nginx-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-server-svc
  namespace: default
  labels:
    app: nginx-server
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-nginx-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations: 
    kubernetes.io/ingress.class: traefik-external
  name: nginx-server
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nginx-argo.beertini.com`)
      priority: 10
      services:
        - name: nginx-server-svc
          port: 80
  tls:
    secretName: local-beertini-com-tls