apiVersion: apps/v1
kind: Deployment
metadata:
  name: meramid-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mermaid
  template:
    metadata:
      labels:
        app: mermaid
    spec:
      containers:
      - name: mermaid-server
        image: ghcr.io/mermaid-js/mermaid-live-editor
        resources:
          requests:
            cpu: 80m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 384Mi
        ports:
        - name: web
          containerPort: 80    
---
apiVersion: v1
kind: Service
metadata:
  name: mermaid-svc
  namespace: default
  labels:
    app: mermaid
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: mermaid
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations: 
    kubernetes.io/ingress.class: traefik-external
  name: mermaid
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`mermaid.beertini.com`)
      priority: 10
      services:
        - name: mermaid-svc
          port: 80
  tls:
    secretName: local-beertini-com-tls